### ISSUE TITLE
Getting different color in both platform

### ISSUE THREAD

**Issue by shrivastavaanurag** [osamaqarem/react-native-image-colors#24]
Hi, thanks for this awesome library, I am using this in one of my react native projects. But my client wants me to get the same exact color for IOS and Android as well, but this library gives different color for the same image. what should I do?

**Comment by osamaqarem** [comment]
This library is a wrapper around the [Palette](https://developer.android.com/reference/androidx/palette/graphics/Palette) class on Android and [UIImageColors](https://github.com/jathu/UIImageColors) on iOS. So because they have different implementation, they can extract different colors for the same image.

There isn't anything you can do. you could tinker with the colors extracted for some image and see which properties are closest to each other in iOS and Android.

you can check if [node-vibrant](https://github.com/Vibrant-Colors/node-vibrant/issues/29) works with react native since its implemented in JS and will get the same colors for both platforms.
