### ISSUE TITLE
build android error Plugin with id 'maven' not found.

### ISSUE THREAD

**Issue by amarkes** [osamaqarem/react-native-image-colors#53]
# Bug

FAILURE: Build failed with an exception.

* Where:
Build file '/Volumes/machd/angulare/app/Studiokore/node_modules/react-native-image-colors/android/build.gradle' line: 23

* What went wrong:
A problem occurred evaluating project ':react-native-image-colors'.
> Plugin with id 'maven' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 36s
antoniomarques@Mac-mini Studiokore % 

![Captura de Tela 2022-05-11 às 10 53 26](https://user-images.githubusercontent.com/6019683/167867028-6aeefa44-cbe5-4b2b-8931-5dff36cff6dd.png)

## Environment info
| Library                   | Version |
| ------------------------- | ------- |
| "react":|  "16.13.1",| 
| "react-native":|  "0.63.2",| 

| Library                   | Version |
| ------------------------- | ------- |
| react-native-image-colors | 1.2.4 |

**Comment by amarkes** [comment]
Upgrade packagem from 1.5.1 erro in pod install
![Captura de Tela 2022-05-11 às 11 11 17](https://user-images.githubusercontent.com/6019683/167870542-cc3aeb86-adad-413f-8805-354b383f9327.png)

**Comment by osamaqarem** [comment]
hey, sorry you're having these troubles. But I'm not clear on how exactly to reproduce it. I think providing steps starting from a barebones React Native project will be very beneficial. It will also help us determine whether the issue is in the library or something related to your specific setup.

> Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

The only thing I noticed is that your Android project uses Gradle 8.0. Currently the latest version of React Native is using 7.3.3 so 8 is likely unsupported.
https://github.com/facebook/react-native/blob/cd4c6659d3477a82f7bf14570ecdd6e9bfb9435e/template/android/gradle/wrapper/gradle-wrapper.properties

**Comment by amarkes** [comment]
thx brow,
good job!
congratulations.
