### ISSUE TITLE
TypeError: null is not an object (evaluating '_module.RNImageColors.getColors')

### ISSUE THREAD

**Issue by aymeric75** [osamaqarem/react-native-image-colors#58]
HEllo, running a very basic Expo Managed app using this library

What I have done:

- npx create-expo-app ExpoProject

- in ExpoProject replace the App.js with the one attached
[App.txt](https://github.com/osamaqarem/react-native-image-colors/files/9970633/App.txt)

- cd ExpoProject

- npx expo install expo-image-picker

- npx expo install expo-image-manipulator

- npm install react-native-image-colors

- npx expo prebuild

- npx expo start

`TypeError: null is not an object (evaluating '_module.RNImageColors.getColors')`

**Comment by osamaqarem** [comment]
hey, I think you missed a step from the instructions. You have to run `expo run:ios` or `expo run:android` after `expo prebuild`.

**Comment by aymeric75** [comment]
But "expo run:ios" can be ran only on a Mac no ? then we lose the advantage of using Expo

**Comment by osamaqarem** [comment]
yea that is right. but that is the point of the `prebuild` command. unfortunate because this library contains custom native code so we need to create a new "expo dev client" which has this new native code.

I'm not sure but I think [eas build](https://docs.expo.dev/build/introduction/) might have some kind of workflow for windows users to develop for iOS (I heard they have a free tier but I cant help here).

**Comment by aymeric75** [comment]
Thanks, so it means that I cannot access the app via Expo Go ?

**Comment by osamaqarem** [comment]
I think that is run automatically as part of the prebuild command. 
The error hints to me that your environment could be misconfigured. If this is the first time you're building native code on this machine (even if it's with expo) I think you need to make sure to do the environment setup [here](https://reactnative.dev/docs/environment-setup) for 'React Native CLI > MacOS > iOS'.

**Comment by aymeric75** [comment]
I have the React Native CLI option, I get the same error. Did you manage to run it on IOS ? if yes could you send me the compiled app ?

**Comment by osamaqarem** [comment]
sorry, but thats not a reasonable request. please try to follow what I suggested in my previous comment for configuring your environment or try to search for the errors your experiencing in setting up your app. 
in any case I think these issues are outside the scope of this library and we should close this issue.

**Comment by aymeric75** [comment]
Hello again,

I have created a repo with all the instruction (REAME.md) to reproduce the error.

Thank you

**Comment by osamaqarem** [comment]
hey! I tried the project but couldn't do this (from the README):

> Then, once the app starts go to select an image on the left column 

this is what I see once the app starts:

<img src="https://user-images.githubusercontent.com/24393922/201133430-2430a5ab-a0af-4d9d-a140-4fb48cacbd6c.png" width="200px" />

**Comment by aymeric75** [comment]
Sorry I am going to update the App.js now

**Comment by osamaqarem** [comment]
hey, so I was able to follow the instructions but I didn't run into the error again. however I think I got the problem you're having now. I think you should not use `npx expo start` but `npx expo start --dev-client` instead. I assumed the app would launch automatically for you after running `expo run:ios`/`expo run:android` and you would skip `expo start`.

here is an image showing the difference. the app icon with an X underneath is the Expo Go app created with the `npx expo start` command. don't use this one anymore. since we are adding custom native code, what we need here is the [custom dev client](https://docs.expo.dev/development/getting-started/#developing-your-app) which got installed when we ran `expo run:ios`/`expo run:android`. now that it is installed, use `npx expo start --dev-client` from now on to start the dev server and open the app with your project name. hope this helps!

<img src="https://user-images.githubusercontent.com/24393922/201141505-7808781c-f8aa-416d-b93f-9edc4144a763.png" width="200px" />

**Comment by aymeric75** [comment]
Thanks a lot, it's working now !

So what I did, in two separate terminals and in this order:

- expo run:android
- npx expo start --dev-client

**Comment by rsys2022** [comment]
Hey i am getting this error on Apple TV
**TypeError: null is not an object (evaluating '_$$_REQUIRE(_dependencyMap[4], "./module").RNImageColors.getColors')**
i am using react native cli
**working platform**
android mobile
android TV
ios mobile


**Libraries**
 "react-native-image-colors": "^1.5.1",
 "react": "17.0.2",
 "react-native": "npm:react-native-tvos@0.66.3-0",

Please help, i am stuck here.
