### ISSUE TITLE
Question: How to get the colors for a portion of an image

### ISSUE THREAD

**Issue by olddustysocksunderthecouch** [osamaqarem/react-native-image-colors#88]
I'd like to use this library to control the color of the text component displayed in front of an image. I want to sample a small part of the image rather than the entire image. If this isn't possible with this lib could you point me in the right direction?

I'd be super grateful for some help! Thanks!

**Comment by osamaqarem** [comment]
That seems like something nice to have built-in support for, but I'm currently occupied. To work around this currently, I'd recommend cropping the image with another package e.g. [expo/ImageManipulator](https://docs.expo.dev/versions/latest/sdk/imagemanipulator/), get either the [base64 or the URI back](https://docs.expo.dev/versions/latest/sdk/imagemanipulator/#imageresult) and pass it to `getColors`.

I'd recommend using the base64 at first to figure things out quickly, but it's probably better to use the URI since it has a lower memory footprint and lets you skip generating the base64 string from the image. Though people have had issues in the past figuring out the [right URI format](https://github.com/TheWidlarzGroup/react-native-video/issues/1572#issuecomment-489347591).
